# Generated by Django 6.1 on 2026-08-12 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_type', models.CharField(choices=[('MOVIE', 'Movie'), ('SHOW', 'TV Show'), ('SPECIAL', 'Special Presentation')], default='MOVIE', max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime_minutes', models.IntegerField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('phase', models.IntegerField(blank=True, null=True)),
                ('release_order', models.IntegerField(blank=True, null=True)),
                ('chronological_order', models.IntegerField(blank=True, null=True)),
                ('importance', models.CharField(choices=[('ESSENTIAL', 'Essential for Doomsday'), ('IMPORTANT', 'Important Context'), ('OPTIONAL', 'Optional / Nice to know'), ('COMPLETIONIST', 'Completionist Only')], default='OPTIONAL', max_length=20)),
                ('why_watch_this', models.TextField(blank=True, null=True)),
                ('saga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='tracker.saga')),
                ('universe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='tracker.universe')),
            ],
        ),
        migrations.AddField(
            model_name='saga',
            name='universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sagas', to='tracker.universe'),
        ),
        migrations.CreateModel(
            name='UserWatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WATCHED', 'Watched 🟢'), ('WATCHING', 'Watching 🟡'), ('NOT_WATCHED', 'Not Watched ⚪'), ('REWATCH', 'Rewatch Recommended 🔴')], default='NOT_WATCHED', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='tracker.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'title')},
            },
        ),
    ]
